name: Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # See: https://github.com/bitovi/github-actions-storybook-to-github-pages
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          build_command: "npm run build-storybook && npx sb-branch-switcher --config .storybook/.branches.json"
          path: dist/storybook-bundle
          # Done manually so we can checkout submodule
          checkout: false
